# Generated by Django 2.2.3 on 2020-03-26 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workitout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=69),
        ),
    ]
